[package]
name = "sciwin"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"

[dependencies]
commonwl.workspace = true
reana.workspace = true
git2.workspace = true
async-trait.workspace = true
async-stream.workspace = true
uuid.workspace = true
thiserror.workspace = true
futures.workspace = true
url.workspace = true
miette.workspace = true
anyhow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tempfile.workspace = true
walkdir.workspace = true
serde_json.workspace = true
chrono.workspace = true
configparser.workspace = true
rand.workspace = true
slugify.workspace = true
serde-saphyr.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
dotenvy.workspace = true
shlex.workspace = true
rstest.workspace = true
fstest.workspace = true
serial_test.workspace = true

[lints]
workspace = true
